### PR TITLE
feat(Constants) & refactor(Stop copying djs)

### PR DESCRIPTION
**Pull request by Nekoyre**

### CODE REVIEW

**Comment by Nekoyre** [comment]
btw i totally didnt copy the idea of constants from djs

**Review by Nciklol — COMMENTED** [review]
This is there because it prevents the client object from showing up in unexpected places

**Comment by Nciklol** [comment]
This is failing ESLint (I'll have to get GitHub to automate that), you can view the errors by doing `npm run lint` in the terminal and also by installing the ESLint extension on VSC.

**Comment by Nekoyre** [comment]
yeah sorry about that i forgot eslint hated prettier

**Review by Nciklol — APPROVED** [review]
LGTM

**Pull request merged**
